{{- if and (not (.Values.iq_server.licenseSecret)) (.Values.iq_server.license) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-iq-server-license-secret
data:
  license_lic: {{ .Values.iq_server.license | b64enc }}
{{- end }}
---
{{- if and (not (.Values.secret.arn)) (not (.Values.iq_server.initialAdminPasswordSecret)) (.Values.iq_server.initialAdminPassword) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-iq-server-initial-admin-password-secret
data:
  password: {{ .Values.iq_server.initialAdminPassword | b64enc }}
{{- end }}
---
{{- if and (not (.Values.secret.rds.arn)) (.Values.iq_server.database.hostname) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-iq-server-database-hostname-secret
data:
  hostname: {{ .Values.iq_server.database.hostname | b64enc }}
{{- end }}
---
{{- if and (not (.Values.secret.rds.arn)) (.Values.iq_server.database.port) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-iq-server-database-port-secret
data:
  port: {{ .Values.iq_server.database.port | toString | b64enc }}
{{- end }}
---
{{- if and (not (.Values.secret.rds.arn)) (.Values.iq_server.database.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-iq-server-database-name-secret
data:
  name: {{ .Values.iq_server.database.name | b64enc }}
{{- end }}
---
{{- if and (not (.Values.secret.rds.arn)) (.Values.iq_server.database.username) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-iq-server-database-username-secret
data:
  username: {{ .Values.iq_server.database.username | b64enc }}
{{- end }}
---
{{- if and (not (.Values.secret.rds.arn)) (not (.Values.iq_server.database.passwordSecret)) (.Values.iq_server.database.password) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-iq-server-database-password-secret
data:
  password: {{ .Values.iq_server.database.password | b64enc }}
{{- end }}
---
{{- if or (and (not (.Values.secret.sshPrivateKey.arn)) (not (.Values.iq_server.sshPrivateKeySecret)) (.Values.iq_server.sshPrivateKey))
    (and (not (.Values.secret.sshKnownHosts.arn)) (not (.Values.iq_server.sshKnownHostsSecret)) (.Values.iq_server.sshKnownHosts)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-iq-server-ssh-secret
data:
  {{- if .Values.iq_server.sshPrivateKey }}
  id_rsa: {{ .Values.iq_server.sshPrivateKey | b64enc }}
  {{- end }}
  {{- if .Values.iq_server.sshKnownHosts }}
  known_hosts: {{ .Values.iq_server.sshKnownHosts | b64enc }}
  {{- end }}
{{- end }}
