{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.iq_server.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- toYaml .Values.serviceAccount.labels | nindent 4 }}
  annotations:
{{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
